export const SEARCHING_SONG = 'SEARCHING_SONG';
export const SEARCH_SONG_SUCCESS = 'SEARCH_SONG_SUCCESS';
export const SEARCH_SONG_FAIL = 'SEARCH_SONG_FAIL';
export const HISTORY_SEARCH_SONG_FAIL = 'HISTORY_SEARCH_SONG_FAIL';
export const SAVE_SONG = 'SAVE_SONG';
export const SAVE_LAST_SONG = 'SAVE_LAST_SONG';
export const SET_INITIAL = 'SET_INITIAL';
